config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  post "contact_created" => "contacts_mailer#contact_created"
  root 'home#index'
  get 'home/about'
  match '/wholesale' , to: "home#wholesale", via: 'get'
  match '/ecommerce' , to: "home#ecommerce", via: 'get'
  match '/retail' , to: "home#retail", via: 'get'
  match '/collaborations' , to: "home#collaboration", via: 'get'
  match '/white-labeling' , to: "home#white_labeling", via: 'get'
  match '/franchise' , to: "home#franchise", via: 'get'
  match '/ceo-tugba' , to: "home#tugba", via: 'get'
  match '/coo' , to: "home#andreas", via: 'get'
  match '/services', to: 'home#services', via: 'get'
  match '/about', to: 'home#about', via: 'get'
  match '/thank-you',  to: 'home#thankyou',via: 'get'
  match '/contact',  to: 'home#contact',via: 'get'
  match '/brands',  to: 'home#brands',via: 'get'
  match '/our-team', to: 'home#team', via: 'get'
  match '/careers', to: 'home#career', via: 'get'
  match '/our-stores', to: 'home#ourstores', via: 'get'
  match '/customer-service' , to: "home#customerservice", via: 'get'
  match '/white-noise-the-label', to: 'home#whitenoise', via: 'get'
  match '/wnx', to: 'home#wnx', via: 'get'
  match '/aziel', to: 'home#aziel', via: 'get'
  match '/wntl', to: 'home#wntl', via: 'get'
  match '/ours', to: 'home#ours', via: 'get'
  match '/heal', to: 'home#heal', via: 'get'
  match '/terms-of-use', to: 'home#terms', via: 'get'
  match '/privacy-policy', to: 'home#privacy-policy', via: 'get'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :contacts, only: [:new, :create]
  
  # resources :notes
  # post 'download/notes', to: 'notes#download'

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < MailForm::Base
    attribute :name,      validate: true
    attribute :email,     validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :phone
    attribute :message
    attribute :nickname,  captcha: true
  
    # Declare the e-mail headers. It accepts anything the mail method
    # in ActionMailer accepts.
    def headers
      {
        :subject => "Contact Form Inquiry",
        :to => "info@auzmena.com",
        :from => %("#{name}" <#{email}>)
      }
    end
  end

app/models/note.rb
class Note < ApplicationRecord
    include ExportCsv
  include ExportPdf
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    add_flash_types :success, :error, :warning
end

app/controllers/concerns/export_csv.rb
module ExportCsv
    extend ActiveSupport::Concern
  
    # module ClassMethods
    module ClassMethods
      def to_csv
        require 'csv'
        options = { col_sep: ';', encoding: 'utf-8' }
        headers = %i[id title]
  
        CSV.generate(headers: true, **options) do |csv|
          csv << headers
  
          all.each do |note|
            csv << [note.id, note.title]
          end
        end
      end
    end
  end

app/controllers/concerns/export_pdf.rb
module ExportPdf
    extend ActiveSupport::Concern
  
    # module ClassMethods
    module ClassMethods
      def to_pdf
        require 'prawn'
        require 'prawn/table'
  
        options = { position: :center, column_widths: [300, 300], width: 600 }
  
        header = %w[ID Title]
        data = all.map { |note| [note.id, note.title] }
        Prawn::Document.new do
          text 'All Notes', align: :center, size: 18, style: :bold
          table([header, *data], header: true, **options)
        end.render
      end
    end
  end
  

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      redirect_to thank_you_url, notice: "Thank you!"

    else
      flash.now[:error] = 'Could not send message'
      render :new
    end
  end 
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def internal_server_error
    render status: 500
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about 
  end

  def brands
  end

  def customerservice
  end

  def terms
  end

  def privacy_policy
  end

  def career
    @contact = Contact.new
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes or /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  def download
    respond_to do |format|
      format.csv { send_data Note.to_csv, filename: "notes-#{Date.today}.csv" }
      format.pdf { send_data Note.to_pdf, filename: "notes-#{Date.today}.pdf" }
    end
end

  # POST /notes or /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to note_url(@note), notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(@note), notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/contacts/create.html.erb
<div class="container">
  <h1>Contact Form</h1>

  <h3>Thank you for your message!</h3>
</div>

app/views/contacts/new.html.erb
<%= form_for @contact do |f| %>

<!-- ====== Contact Section Start -->
   <section class="bg-white py-20 lg:py-[120px] overflow-hidden relative z-10 px-8">
      <div class="container">
         <div class="flex flex-wrap lg:justify-between -mx-4">
            <div class="w-full lg:w-1/2 xl:w-6/12 px-4">
               <div class="max-w-[570px] mb-12 lg:mb-0">
                  <h2
                     class="
                     text-dark
                     mb-6
                     uppercase
                     font-bold
                     text-[32px]
                     sm:text-[40px]
                     lg:text-[36px]
                     xl:text-[40px]
                     "
                     >
                     GET IN TOUCH WITH US
                  </h2>
                  <p class="text-base text-body-color leading-relaxed mb-9">
                     We will get back to you as soon as possible.
                  </p>

                  <div class="flex mb-8 w-full">
                     <div>
                        <%= image_tag "contact1.jpg" %>
                     </div>

                  </div>

               </div>
            </div>
            <div class="w-full lg:w-1/2 xl:w-5/12 px-4">
               <div class="bg-white relative rounded-lg p-8 sm:p-12 shadow-lg">
                  <%= form_for @contact do |f| %>
                     <div class="mb-6">
                        <h4 class="block mb-4 text-base text-primary-600 font-semibold">
                          Contact Us - Love to Hear From You
                        </h4>
                        <%= f.text_field  :name, required: true, class:"w-full
                           rounded
                           py-3
                           px-[14px]
                           text-body-color text-base
                           border border-[f0f0f0]
                           outline-none
                           focus-visible:shadow-none
                           focus:border-indigo-600",placeholder: "Full Name" %>
                     </div>
                     <div class="mb-6">
                        <%= f.text_field :email, required: true, class: "w-full
                           rounded
                           py-3
                           px-[14px]
                           text-body-color text-base
                           border border-[f0f0f0]
                           outline-none
                           focus-visible:shadow-none
                           focus:border-indigo-600", placeholder:"your@email.com" %>
                     </div>
                     <div class="mb-6">
                        <%= f.text_field :phone, required: true, class: "w-full
                           rounded
                           py-3
                           px-[14px]
                           text-body-color text-base
                           border border-[f0f0f0]
                           outline-none
                           focus-visible:shadow-none
                           focus:border-indigo-600", placeholder:"Your Phone" %>
                     </div>
                     <div class="mb-6">
                        <%= f.select :phone, ["LOGISTICS","CREATIVE TEAM","E-COMMERCE ","FACTORY TEAM","HUMAN RESOURCES","ACCOUNTING","LEGAL","ADMINISTRATOR","SALES ","MARKETING","PHOTOGRAPHER","VIDEOGRAPHER"],{:prompt => "Contact Reason"},{class: "w-full
                           rounded
                           py-3
                           px-[14px]
                           text-body-color text-base
                           border border-[f0f0f0]
                           outline-none
                           focus-visible:shadow-none
                           focus:border-indigo-600"} %>

                     </div>
                     <div class="mb-6">
                        <%= f.text_area :message, rows: 8, cols: 40, required: true, class: " w-full
                           rounded
                           py-3
                           px-[14px]
                           text-body-color text-base
                           border border-[f0f0f0]
                           resize-none
                           outline-none
                           focus-visible:shadow-none
                           focus:border-indigo-600",
                           placeholder: "Send me a message"%>
                     </div>
                     <div class= "d-none">
                        <%= f.text_field :nickname, :hint => 'Leave this field blank!', style: 'display:none' %>
                     </div>
                     <div>
                        <%= f.submit 'Submit', class: 'w-full
                           text-white
                           bg-indigo-700
                           rounded
                           border border-primary
                           p-3
                           transition
                           hover:bg-opacity-90' %>
                     </div>
                  <% end %>
               </div>
            </div>
         </div>
      </div>
   </section>
<% end %>

app/views/home/about.html.erb
<!-- ====== About Section Start -->
<section class="pt-20 lg:pt-[120px] pb-12 lg:pb-[90px] overflow-hidden bg-white px-8">
   <div class="container">
      <div class="flex flex-wrap justify-between items-center -mx-4">
         <div class="w-full lg:w-6/12 px-4">
            <%= image_tag ("ABOUT-US-PAGE/IMAGE.jpg") , class:"rounded-2xl w-full" %>
         </div>
         <div class="w-full lg:w-1/2 xl:w-5/12 px-8">
            <div class="mt-10 lg:mt-0">
               <h2 class="font-bold text-3xl sm:text-4xl text-neutral-800 mb-8">
                  About Us ?
               </h2>
               <p class="text-base text-body-color mb-8 text-neutral-800">
                  Auzmena Trading LLC was established in 2016 and is currently based in Dubai, U.A.E. The
                  multi-holding company focuses on franchising international master brands throughout the
                  MENA region along with its own in-house production. The aim is to expand the market for all the
                  affiliated brands throughout the Middle-east, Europe and the US. With a lot of new investors
                  coming on board, AUZMENA is constantly sourcing new brands and growing the team through
                  online platforms and new stores across the Middle-East.
               </p>
               <h3 class="font-bold text-1xl text-lg text-neutral-800 mb-8">
                  IN-HOUSE PRODUCTION
               </h3>
               <p class="text-base text-body-color mb-12 text-neutral-800">
                  The in-house brand was established in 2016 and named White Noise The Label. The label is the center of creativity, in which all our designs and products are carefully picked to appeal to the current fashion trends. 
                  The brand’s focus is quality and unique products at affordable prices.
               </p>
               <%= link_to "Contact Us", new_contact_url, class:"text-center inline-block block w-full rounded bg-indigo-600 my-3 px-12 py-3 text-sm font-medium text-white shadow hover:bg-indigo-700 focus:outline-none focus:ring active:bg-indigo-500 sm:w-auto" %>
            </div>
         </div>
      </div>
   </div>
</section>
<!-- ====== About Section End -->

app/views/home/andreas.html.erb
<main class="profile-page">
      <section class="relative block" style="height: 500px;">
        <div
          class="absolute top-0 w-full h-full bg-center bg-cover"
          style='background-image: url("https://images.unsplash.com/photo-1469002372271-3406b43e1f27?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80");'
        >
          <span
            id="blackOverlay"
            class="w-full h-full absolute opacity-50 bg-black"
          ></span>
        </div>
        <div
          class="top-auto bottom-0 left-0 right-0 w-full absolute pointer-events-none overflow-hidden"
          style="height: 70px;"
        >
          <svg
            class="absolute bottom-0 overflow-hidden"
            xmlns="http://www.w3.org/2000/svg"
            preserveAspectRatio="none"
            version="1.1"
            viewBox="0 0 2560 100"
            x="0"
            y="0"
          >
            <polygon
              class="text-gray-300 fill-current"
              points="2560 0 2560 100 0 100"
            ></polygon>
          </svg>
        </div>
      </section>
      <section class="relative py-16 bg-gray-300">
        <div class="container mx-auto px-4">
          <div
            class="relative flex flex-col min-w-0 break-words bg-white w-full mb-6 shadow-xl rounded-lg -mt-64"
          >
            <div class="px-6">
              <div class="flex flex-wrap justify-center">
                <div class="w-full lg:w-3/12 px-4 lg:order-2 flex justify-center">
                  <div class="relative">
                    <img
                      alt="..."
                      src="https://media-exp1.licdn.com/dms/image/C4E03AQGnF2O3X9Xhew/profile-displayphoto-shrink_800_800/0/1643357650899?e=2147483647&v=beta&t=dkGT2pYa41kI1bbMSQ-kezzpo1C1XpAhdkrRYPJkZk0"
                      style="max-width: 150px;"
                      class="shadow-xl rounded-full h-auto align-middle border-none absolute -m-16 -ml-20 lg:-ml-16"

                    />
                  </div>
                </div>
                <div
                  class="w-full lg:w-4/12 px-4 lg:order-3 lg:text-right lg:self-center"
                >
                  <div class="py-6 px-3 mt-32 sm:mt-0">
                    <a
                      class="bg-indigo-500 active:bg-indigo-600 uppercase text-white font-bold hover:shadow-md shadow text-xs px-4 py-2 rounded outline-none focus:outline-none sm:mr-2 mb-1"
                      type="button"
                      style="transition: all 0.15s ease 0s;"
                      href="mailto:andreas@auzmena.com"
                    >
                      Connect
                    </a>
                  </div>
                </div>
                <div class="w-full lg:w-4/12 px-4 lg:order-1">
                  <div class="flex justify-center py-4 lg:pt-4 pt-8">
                    <div class="mr-4 p-3 text-center">
                      <span
                        class="text-xl font-bold block uppercase tracking-wide text-gray-700"
                        >10</span
                      ><span class="text-sm text-gray-500">Projects</span>
                    </div>
                    <div class="mr-4 p-3 text-center">
                      <span
                        class="text-xl font-bold block uppercase tracking-wide text-gray-700"
                        >10</span
                      ><span class="text-sm text-gray-500">Stores</span>
                    </div>
                    <div class="lg:mr-4 p-3 text-center">
                      <span
                        class="text-xl font-bold block uppercase tracking-wide text-gray-700"
                        >30</span
                      ><span class="text-sm text-gray-500">Collaborations</span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="text-center mt-12">
                <h3
                  class="text-4xl font-semibold leading-normal mb-2 text-gray-800 mb-2"
                >
                  Andreas Pehl
                </h3>
                <div
                  class="text-sm leading-normal mt-0 mb-2 text-gray-500 font-bold uppercase"
                >
                  <i
                    class="fas fa-map-marker-alt mr-2 text-lg text-gray-500"
                  ></i>
                  Istanbul, Turkey
                </div>
                <div class="mb-2 text-gray-700 mt-10">
                  <i class="fas fa-briefcase mr-2 text-lg text-gray-500"></i
                  >Chief Operating Officer - Auzmena LLC
                </div>

              </div>
              <div class="mt-10 py-10 border-t border-gray-300 text-center">
                <div class="flex flex-wrap justify-center">
                  <div class="w-full lg:w-9/12 px-4">
                    <p class="mb-4 text-md leading-relaxed text-gray-800">
                      Andreas Pehl started his career in retail as a salesperson before he moved to Esprit de corp. In Germany.
                      During his 12 years with that company,he climbed his steps to become the chief buyer and setting up 
                      a completely new supplier base in Turkey and Portugal.<br/><br/>
                      After the global economic crisis hit, Andreas became the director of merchandising and administration of the Turkish liaison 
                      office of the german ladies wear brand and further moved on to become the country director/ Turkey of the Tel Aviv based company, 
                      Cherryfield Ltd. During the 6 years with this very company, Andreas increased their profit to 400%. 

                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </main>

app/views/home/aziel.html.erb
<section class="overflow-hidden h-500 aziel-banner bg-bottom bg-cover bg-no-repeat">
  <div class="bg-black/25 p-8 md:p-12 lg:px-16 lg:py-24 banner_paddding">
    <div class="max-w-lg text-center sm:text-left">
      <h2 class="text-2xl font-bold text-white sm:text-3xl md:text-5xl">
        Aziel
      </h2>

      <p
        class="max-w-md text-white/90 md:mt-6 md:block md:text-lg md:leading-relaxed"
      >
        Welcome to Aziel Online Shop! Men's Shoes
      </p>

      <div class="mt-4 sm:mt-8">
        <a
          href="https://www.whitenoisethelabel.com/"
          class="inline-flex items-center rounded-full bg-black px-8 py-3 text-white shadow-lg transition focus:outline-none focus:ring"
        >
          <span class="text-sm font-medium"> Order Now </span>

          <svg
            class="ml-3 h-5 w-5"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M17 8l4 4m0 0l-4 4m4-4H3"
            />
          </svg>
        </a>
      </div>
    </div>
  </div>
</section>

<section class="bg-white">
  <div class="mx-auto max-w-screen-xl px-4 py-12 sm:px-6 lg:px-8">
    <div class="text-center">

      <div style="text-align: -webkit-center; "> <%= image_tag "aziel.png",:style=>"max-width: 240px;" %> </div>
      <br>
      <h2 class="text-lg font-bold">Our Products</h2>

      <p class="text-2xl font-medium" style="color: black;">
        Handmade with love
      </p>
    </div>

    <div class="swiper mt-8" style="background-color:white;">
      <div class="swiper-wrapper">

        <div class="swiper-slide">
          <a href="https://www.whitenoisethelabel.com/collections/all" class="block">
            <div>
              <p class="text-xs  brown_color">Aziel</p>

              <h3 class="font-bold">Men Fashion</h3>
            </div>

            <%= image_tag "Azeil/1.jpeg", :class=>"aspect-[3/4] w-full object-cover" %>


          </a>
        </div>

        <div class="swiper-slide">
          <a href="https://www.whitenoisethelabel.com/collections/all" class="block">
            <div>
              <p class="text-xs  brown_color">Aziel</p>

              <h3 class="font-bold">Men Fashion</h3>
            </div>

            <%= image_tag "Azeil/2.jpeg", :class=>"aspect-[3/4] w-full object-cover" %>


          </a>
        </div>

        <div class="swiper-slide">
          <a href="https://www.whitenoisethelabel.com/collections/all" class="block">
            <div>
              <p class="text-xs  brown_color">Aziel</p>

              <h3 class="font-bold">Men Fashion</h3>
            </div>

            <%= image_tag "Azeil/3.jpeg", :class=>"aspect-[3/4] w-full object-cover" %>


          </a>
        </div>

        <div class="swiper-slide">
          <a href="https://www.whitenoisethelabel.com/collections/all" class="block">
            <div>
              <p class="text-xs  brown_color">Aziel</p>

              <h3 class="font-bold">Men Fashion</h3>
            </div>

            <%= image_tag "Azeil/4.jpeg", :class=>"aspect-[3/4] w-full object-cover" %>


          </a>
        </div>
      </div>

      <div class="swiper-pagination !relative !bottom-0 mt-12"></div>
    </div>
  </div>
</section>

<script>
  new Swiper('.swiper', {
    loop: true,
    spaceBetween: 32,
    slidesPerView: 1,
    pagination: {
      clickable: true,
      el: '.swiper-pagination',
    },
    breakpoints: {
      640: {
        slidesPerView: 2,
      },
      1024: {
        slidesPerView: 4,
      },
    },
  })
</script>

app/views/home/collaboration.html.erb
<section class="overflow-hidden bg-white sm:grid sm:grid-cols-2 p-5">
  <div class="p-8 md:p-12 lg:px-16 lg:py-24">
    <div class="mx-auto max-w-xl text-center sm:text-left">
      <h2 class="text-2xl font-bold text-gray-900 md:text-3xl">
        Women's Footwear and luxury bags Collaborations
      </h2>

      <div class="mt-4 md:mt-8">
        <a href="#" class="inline-block rounded bg-indigo-600 px-12 py-3 text-sm font-medium text-white transition hover:bg-indigo-700 focus:outline-none focus:ring focus:ring-yellow-400" style="background-color: black;">
          Want to Collab with us?
        </a>
      </div>
    </div>
  </div>
  <div>
    <%= image_tag "Collab-page/IMAGE-UPPER-1.jpg",:class=>"",:style=>"max-height: 500px; object-fit: contain; float:left; margin: 0 15px;" %>
    <%= image_tag "Collab-page/IMAGE-UPPER-2.jpg",:class=>"",:style=>"max-height: 500px; object-fit: contain;" %>
  </div>
</section>

<section class="overflow-hidden bg-white sm:grid sm:grid-cols-2 p-5 mt-10">
  <div style="">
    <%= image_tag "Collab-page/IMAGE-LOWER-1.jpg", :class=>"object-cover",:style=>"max-height: 500px; float:left;margin: 0 15px;" %>
    <%= image_tag "Collab-page/IMAGE-LOWER-2.jpg", :class=>"object-cover",:style=>"max-height: 500px" %>
  </div>

  <div class="p-8 md:p-12 lg:px-16 lg:py-24">
    <div class="mx-auto max-w-xl text-center sm:text-left">
      <h4 class="font-bold text-3xl mb-4 text-neutral-800">AUZMENA AFFILIATE PROGRAM</h4>

      <div class="mt-4 md:mt-8">
        <p class="mb-6 text-neutral-800">
         White Noise The Label collaborates with influencers to create their own signature collection under the brand name based on their personal preference, style and unique approach. These products are then promoted by the influencers on their social media platforms, showcasing their unique style for followers to purchase directly from our online platform.

        </p>
      </div>
    </div>
  </div>
</section>

<%= render "layouts/services"%>

app/views/layouts/_logos.html.erb
<section class="logosection" >
    <%= image_tag "1", class:'logoslide' %>
    <%= image_tag "2", class:'logoslide' %>
    <%= image_tag "3", class:'logoslide' %>
    <%= image_tag "4", class:'logoslide' %>
</section>

app/views/layouts/_sections.html.erb
<div class="hero h-95 home_banner">
  <div class="hero-content text-center text-white">
    <!-- <div class="max-w-md">
      <h1 class="mb-5 text-5xl font-bold">AUZMENA</h1>
    </div> -->
  </div>
</div>

<!-- <section>
  <div>
    <div id="downloads-filter" class="position-relative d-none d-lg-flex align-items-center justify-content-around flex-wrap">
      <div class="faq-product-buttons text-center inspiration-menu dark_pink">
        <a href="#about"><span>About</span></a>
        <a href="#services"><span>Services</span></a>
        <a href="#Luxury Rooms"><span>Join Us</span></a>
        <a href="#Trends"><span>Team</span></a>
      </div>
    </div>
  </div>
</section> -->

<section class="bg-white">
  <div class="p-8 md:p-12 lg:px-16 lg:py-24">
    <div class="mx-auto max-w-lg text-center">
      <h2 class="text-2xl font-bold md:text-3xl dark_pink" style="font-size: 35px;">
        WHO WE ARE
      </h2>
      <p class="text-black sm:mt-4 sm:block dark_pink" style="font-size: 21px;">
        Auzmena Trading LLC was established in 2016 and is currently based in Dubai, U.A.E.
        The company focuses on franchising international master brands throughout the MENA region along with its recent in-house production of footwear.
        <br/>
        <a href="/about">
      <div class="mt-4 inline-block border-b border-pink pb-1 font-medium dark_pink">
        Find out more
      <span aria-hidden="true">&rarr;</span>
      </div>
      </a>
      </p>
    </div>
  </div>
</section>

<section
  class="overflow-hidden bg-fixed bg-cover bg-center bg-no-repeat mid_section">
  <div class="bg-black/25 p-20 md:p-12 lg:px-16 lg:py-24">
    <div class="max-w-lg text-center sm:text-left">
      <h2 class="text-2xl font-bold sm:text-3xl md:text-5xl" style="color: white;">
        IN-HOUSE PRODUCTION
      </h2>
      <p class="hidden max-w-md md:mt-6 md:block md:text-lg md:leading-relaxed" style="color: white;">
        Our footwear factory is located in Istanbul Turkey, offering recent trend designs, one stop solution, and high quality manufacturing.
      </p>
      <div class="mt-4 sm:mt-8">
        <%= link_to "Get in touch", new_contact_url, class:"text-center inline-block block w-full rounded bg_dark_pink my-3 px-12 py-3 text-sm font-medium text-white shadow hover:bg-gray-700 focus:outline-none focus:ring active:bg-primary-500 sm:w-auto" %>
      </div>
    </div>
  </div>
</section>
<!-- Section 2 -->

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/notes/_note.html.erb
<div id="<%= dom_id note %>">
  <p>
    <strong>Title:</strong>
    <%= note.title %>
  </p>

</div>